export const stories = [
  {
    title: "Salem's Night Watch",
    slug: "salems-night-watch",
    date: "2022-02-13T20:00:00-04:00",
    text: "<p>Have you ever seen your cat lash out, attacking some unseen creature that's always just out of reach?  Have you seen them panic and dash across the floor only to turn tail and run back to their original spot, pouncing?  Have you ever seen them stare so intently at a spot on the wall, you think they might just be seeing something you don’t?  Your cat has been hunting greebles.</p><p>Most people think that when cats were first domesticated, humans wanted them to keep the rodent population in check around our stored food.  This might hold a grain of truth, but the main reason was much more desperate:  our reality was being attacked by horrific creatures from Beyond the Gate, and cats were among the only beings that could see them.  We hunted with them, and together, we pushed the greebles back.</p><p>For a while, the world was safe, and humans developed while cats domesticated themselves.  Tales of the horrific creatures turned to legends of monsters, which were in turn swallowed into myth.  There were sometimes minor breaches of reality every once in a while, but our cats remembered how to keep us safe by passing down the ancient, magical traditions they first discovered with our ancestors.</p><p>  Humans, for the most part, forgot.  Sarah Styles, at least, did not have any idea what a greeble was.  She had not heard of the Gate.  She hadn’t even heard of the Signs or The Covenant that was about to save her life.  She knew that her cat, Salem, definitely loved her, but she had no idea how far he would go to keep her safe.</p>",
  },
  {
    title: "Knot in Time",
    slug: "salems-night-watch",
    date: "2022-04-24T20:00:00-04:00",
    text: "<p>When time travel was legalized and regulated in 2395, it was widely considered a frivolous political stunt: good for building support from science fiction fans and conspiracy theorists, but otherwise a waste of time and resources.  As such, the small auditorium in downtown London (supposedly near the site of HG Wells’ original publishing house, though there is some debate on that point) proved woefully inadequate when May 7, 2395 EST (Earth Standard Time) turned out to be the most important date in the history of the universe.</p><p> Though the text would be quickly amended, the first version of the Time Traveler’s Treaty was a simple, one sentence declaration: “From this moment forward, time travel shall be legalized on the planet Earth.”  The second that the 21st President of the World lifted their pen from the paper, finishing their signature in front of the few dozen politicians and newspapers that deemed the event worthy of their time, a thunderous uproar of applause shook the entire city as millions of time travelers from the entire history of mankind appeared on the spot.</p><p> With them, they brought time traveling technology, and the revised draft of the Time Traveler’s Treaty, which had already been written tomorrow.  And nothing has been the same since.  As a time traveling historian, this was always Jaelys Winstead’s favorite story.</p><p> But it was not his story.</p><p> His story would be much darker.</p>"
  }
]