# Generated by Django 4.1.7 on 2023-02-23 22:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(default='', max_length=100, unique=True)),
                ('date', models.DateField()),
                ('text', ckeditor.fields.RichTextField(default='')),
            ],
        ),
    ]
